name: API Tests

on:
  push:         
    branches:
      - master     
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1-5"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the Project
        run: mvn clean install -DskipTests=true

      - name: Run API tests with Maven
        run: mvn test

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: report-deployment
          path: previous-report

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: previous-report
          allure_history: allure-history
          allure_results: allure-results

      - name: Get latest report folder
        id: get_report
        if: always()
        run: |
          echo "ðŸ“‚ Checking allure-history contents..."
          ls -lt allure-history | head -20
          
          # Láº¥y folder má»›i nháº¥t theo thá»i gian cáº­p nháº­t
          latest=$(ls -1t allure-history | grep -E '^[0-9]+$' | head -1)

          echo "âœ… Latest report folder (just created): $latest"
          echo "LATEST=$latest" >> $GITHUB_ENV
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: report-deployment
          publish_dir: allure-history

      - name: Show Report Link
        if: always()
        run: echo "Allure Report available at https://htuanln97.github.io/java-api-test/$LATEST/"

      - name: Notify Slack
        if: always()
        run: |
          STATUS=${{ job.status }}
          RUN_NUMBER=${{ github.run_number }}
          REPO=${{ github.repository }}
          RUN_URL="https://github.com/$REPO/actions/runs/${{ github.run_id }}"
    
          curl -X POST -H 'Content-type: application/json' \
          --data "{
          \"text\": \":robot_face: API Tests *$STATUS* â€” Report: https://htuanln97.github.io/java-api-test/$LATEST/ â€” <${RUN_URL}|GitHub Actions Run #${RUN_NUMBER}> \"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}


